const searchData = [
    "JavaScript for Beginners",
    "Learn Python: Complete Guide",
    "Mastering React.js",
    "Introduction to Data Science",
    "Web Development Bootcamp",
    "Machine Learning Basics",
    "Deep Learning with TensorFlow",
    "Understanding Artificial Intelligence",
    "Mobile App Development with Flutter",
    "Introduction to SQL Databases",
    "Advanced CSS Techniques",
    "Node.js for Backend Development",
    "How to Build RESTful APIs",
    "Frontend Development with Angular",
    "Fullstack Development with MERN",
    "Cybersecurity Basics",
    "Ethical Hacking for Beginners",
    "Cloud Computing with AWS",
    "Blockchain Development",
    "DevOps Essentials",
    "Kubernetes: A Comprehensive Guide",
    "Docker for Developers",
    "UI/UX Design Fundamentals",
    "Game Development with Unity",
    "Virtual Reality Development",
    "Augmented Reality Applications",
    "Digital Marketing Mastery",
    "SEO Techniques for Websites",
    "Social Media Marketing",
    "Learn Graphic Design",
    "Video Editing for Beginners",
    "Photography Masterclass",
    "Financial Accounting Basics",
    "Excel for Business Analytics",
    "Cryptocurrency Investment",
    "Stock Market Trading",
    "Public Speaking Essentials",
    "Time Management Techniques",
    "Entrepreneurship 101",
    "E-commerce Development",
    "How to Start a Blog",
    "Writing for the Web",
    "Creative Writing Workshop",
    "English Grammar Essentials",
    "SAT Preparation Course",
    "TOEFL Mastery Guide",
    "IELTS Preparation Made Easy",
    "Mastering French Language",
    "Spanish for Beginners",
    "Learning Mandarin Chinese",
    "Coding for Kids",
    "Robotics for Teens",
];

export default searchData;
